server:
  servlet:
    context-path: /api/v1/eventservice
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${DB_URL:jdbc:postgresql://localhost:5432}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    ru.udisondev.eventservice: ${APP_LOG_LEVEL:INFO}